export const plans = [
    {
      key: "free",
      name: "Free",
      description: "Try the chatbot with free credits",
      price: 0,
      billingCycle: "one-time",
      credits: 50,
      imageCost: 5,
      features: [
        "AI chat generation",
        "Image generation (5 credits per image)",
        "50 free credits",
        "Basic response speed",
        "Community support",
      ],
      limits: {
        dailyRequests: 20,
        maxImagesPerDay: 5,
      },
      isPremium: false,
      isPopular: false,
    },
    {
      key: "monthly",
      name: "Monthly",
      description: "Perfect for regular users",
      price: 700,
      billingCycle: "month",
      credits: 500,
      imageCost: 5,
      features: [
        "Unlimited AI chat",
        "Image generation (5 credits per image)",
        "500 monthly credits",
        "Faster response speed",
        "Priority support",
        "Chat history saved",
      ],
      limits: {
        dailyRequests: "Unlimited",
        maxImagesPerDay: 50,
      },
      isPremium: false,
      isPopular: true,
    },
    {
      key: "yearly",
      name: "Yearly",
      description: "Best value for power users & teams",
      price: 6720,
      billingCycle: "year",
      credits: 7000,
      imageCost: 5,
      features: [
        "Everything in Monthly plan",
        "7000 yearly credits",
        "Save 20% with annual billing",
        "Ultra-fast responses",
        "Dedicated support",
        "Early access to new features",
        "Custom image styles",
      ],
      limits: {
        dailyRequests: "Unlimited",
        maxImagesPerDay: "Unlimited",
      },
      isPremium: true,
      isPopular: false,
    },
  ];